sudo: required
language: node_js
node_js:
  - "10"
notifications:
  webhooks: https://prod-73.westeurope.logic.azure.com:443/workflows/b40cfae8973245b0bf31a4ad224e9e6f/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=hIQg1np0SHai9RgG8LLbT_4-RozahYesRR6XtG-EyAA
  on_success: never
